spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pwp67_dev
    username: postgres
    password: postgres
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    ec.edu.ups.pwp67: DEBUG

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWT2024MustBeAtLeast256BitsLongForHS256Algorithm}
  expiration: 3600000